blank_issues_enabled: false
contact_links:
  - name: "\U0001F4A1 Model Providers & Plugins"
    url: "https://github.com/AutoAgents-ai/docs/issues/new/choose"
    about: Report issues with model providers or plugins and include relevant version details.
  - name: "\U0001F4E7 Discussions"
    url: https://github.com/AutoAgents-ai/docs/discussions
    about: General discussions and seek help from the community
